name: Let's Talk Taalcoaching

markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

description: Taallessen engels voor iedereen
url: http://www.lets-talk-taalcoaching.be
keywords:
  - taallessen
  - engels
  - taalcoach
  - toerisme
  - privélessen
  - bijlessen
  - Oostende
  - Brugge
  - volwassenonderwijs
  - secundair onderwijs

links:
  social-fb: https://www.facebook.com/LetsTalkTaalcoaching
  social-tw: https://twitter.com/fabiennesegaert
  social-in: https://www.linkedin.com/in/fabiennesegaert
  mail: fabienne@lets-talk-taalcoaching.be
